[project]
name = 'pynenc'
version = "0.0.0"
description = 'A simple task management system for complex distributed orchestration'
readme = 'README.md'
authors = [{name = 'Jose Diaz', email='open.source.route@gmail.com'}]
license = {file = 'LICENSE'}
requires-python = '>=3.11'
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Distributed Computing",
]

[project.urls]
homepage = 'https://pynenc.org'
documentation = 'https://pynenc.org/docs/'
repository = 'https://github.com/pynenc/pynenc'
dependencies = [
    "redis==4.6.0",
]

[tool.black]
line-length = 88
target-version = ['py311']
required-version = '23.3.0'
exclude = '''
/(
  \.mypy_cache
  | env
  | venv
)/
'''

[tool.ruff]
line-length = 88
update-check = false
target-version = "py311"
fix = true
unfixable = []
exclude = [
  ".eggs/*.py",
  ".venv",
  ".env",
]

[tool.mypy]
files = ["pynenc"]
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
exclude = 'venv,env'
show_error_codes = true
pretty = true
allow_redefinition = true
no_implicit_optional = true
strict_equality = true

[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "line-too-long",
  "too-many-ancestors",
  "too-many-arguments",
  "too-many-boolean-expressions",
  "too-many-branches",
  "too-many-function-args",
  "too-many-instance-attributes",
  "too-many-locals",
  "too-many-nested-blocks",
  "too-many-public-methods",
  "too-many-return-statements",
  "too-many-statements",
]

[tool.pylint.master]
ignore = "venv,env"


[project.optional-dependencies]
test = [
    "pytest >=7.3.1,<8.0.0",
    "coverage[toml] >= 7.2.6,< 8.0",
    "mypy ==1.3.0",
    "ruff ==0.0.270",
    "black == 23.3.0",
    "types-redis == 4.6.0.2",
]

[pytest]
log_cli = true