name: Smokeshow

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

permissions:
  statuses: write

jobs:
  smokeshow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"

      - run: pip install smokeshow

      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Tests
          commit: ${{ github.event.workflow_run.head_sha }}
          name: coverage-html
          path: coverage-html

      - name: Download integration test coverage artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Tests
          commit: ${{ github.event.workflow_run.head_sha }}
          name: coverage-html-integration
          path: coverage-html-integration

      - run: coverage combine coverage-html coverage-html-integration

      - run: smokeshow upload combined-coverage/
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 100
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
